buildscript {
    ext {
        gdxVersion = '1.12.1'
    }
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.2'
    }
}

allprojects {
    apply plugin: 'eclipse'

    version = '1.0'

    repositories {
        mavenLocal()
        mavenCentral()
        google()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        maven { url 'https://s01.oss.sonatype.org' }
    }
}

configure(project(':core')) {
    apply plugin: 'java-library'

    sourceCompatibility = 17
    targetCompatibility = 17

    dependencies {
        api "com.badlogicgames.gdx:gdx:$gdxVersion"
    }
}

configure(project(':android')) {
    apply plugin: 'com.android.application'

    dependencies {
        implementation project(':core')
        api "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi-v7a"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-arm64-v8a"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86_64"
    }
}
